apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  initContainers:
    - name: configurator-init
      image: gcr.io/hightowerlabs/configurator:0.1.0
      args:
        - "-config=/etc/app/app.json"
        - "-onetime"
  containers:
    - name: app
      image: gcr.io/hightowerlabs/app:0.2.0
      args:
        - "-config=/etc/app/app.json"
      resources:
        limits:
          cpu: "100m"
          memory: "50Mi"
      ports:
        - containerPort: 80
          hostPort: 80
